In [1]:
!pip install beautifulsoup4 as bs4

Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/66/25/ff030e2437265616a1e9b25ccc864e0371a0bc3adb7c5a404fd661c6f4f6/beautifulsoup4-4.9.1-py3-none-any.whl (115kB)
     |████████████████████████████████| 122kB 6.3MB/s eta 0:00:01
Collecting as
  Downloading https://files.pythonhosted.org/packages/b4/08/226c133ec497d25a63edb38527c02db093c7d89e6d4cdc91078834486a5d/as-0.1-py3-none-any.whl
Collecting bs4
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting soupsieve>1.2 (from beautifulsoup4)
  Downloading https://files.pythonhosted.org/packages/6f/8f/457f4a5390eeae1cc3aeab89deb7724c965be841ffca6cfca9197482e470/soupsieve-2.0.1-py3-none-any.whl
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/a0/b0/b2/4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
Successfully built bs4
Installing collected packages: soupsieve, beautifulsoup4, as, bs4
Successfully installed as-0.1 beautifulsoup4-4.9.1 bs4-0.0.1 soupsieve-2.0.1

In [30]:
from bs4 import BeautifulSoup as soup
import requests
import pandas as pd
import numpy as np

In [31]:
# download data in the url
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
rawtext = requests.get(url).text
dsoup = soup(rawtext, "html.parser")

#finding the table element
toronto = dsoup.find('table', class_='wikitable sortable')

In [55]:
#table clean
dt = []
for row in toronto.find_all('tr'):
    col = row.find_all('td')
    if len(col) == 3:
        dt.append((col[0].text.strip(), col[1].text.strip(), col[2].text.strip()))
        
#into dataframe
df = pd.DataFrame(np.asarray(dt))
df.columns = ['PostalCode', 'Borough', 'Neighborhood']

df['Neighborhood'] = df['Neighborhood'].str.replace(']', '')

df.replace('Not assigned', np.nan, inplace=True)

df.head(10)

  PostalCode           Borough                                 Neighborhood
0        M1A               NaN                                          NaN
1        M2A               NaN                                          NaN
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7        M8A               NaN                                          NaN
8        M9A         Etobicoke      Islington Avenue, Humber Valley Village
9        M1B       Scarborough                               Malvern, Rouge

The next step is to add neighbourhood to a borough where a neighborhood is Not assigned (NaN).

In [56]:
n = len(df.index)
for i in range(0, n):
    if df.iloc[i,1] is not np.nan and df.iloc[i,2] is np.nan:
        df.iloc[i,2] = df.iloc[i,1]
df.head(10)

  PostalCode           Borough                                 Neighborhood
0        M1A               NaN                                          NaN
1        M2A               NaN                                          NaN
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7        M8A               NaN                                          NaN
8        M9A         Etobicoke      Islington Avenue, Humber Valley Village
9        M1B       Scarborough                               Malvern, Rouge

Next step: Dropping not assigned boroughs

In [57]:
df.dropna(inplace=True)

Final step in cleaning: grouping neighborhoods in the same borough separated by commas

In [58]:
df = df.groupby(['PostalCode', 'Borough'])['Neighborhood'].apply(', '.join).reset_index()
df.head(10)

  PostalCode      Borough                                     Neighborhood
0        M1B  Scarborough                                   Malvern, Rouge
1        M1C  Scarborough           Rouge Hill, Port Union, Highland Creek
2        M1E  Scarborough                Guildwood, Morningside, West Hill
3        M1G  Scarborough                                           Woburn
4        M1H  Scarborough                                        Cedarbrae
5        M1J  Scarborough                              Scarborough Village
6        M1K  Scarborough      Kennedy Park, Ionview, East Birchmount Park
7        M1L  Scarborough                  Golden Mile, Clairlea, Oakridge
8        M1M  Scarborough  Cliffside, Cliffcrest, Scarborough Village West
9        M1N  Scarborough                      Birch Cliff, Cliffside West

In [59]:
print (df.shape)

(103, 3)

In [60]:
!wget -O Geospatial_Coordinates.csv http://cocl.us/Geospatial_data

--2020-06-17 16:56:28--  http://cocl.us/Geospatial_data
Resolving cocl.us (cocl.us)... 169.48.113.194, 158.85.108.86, 158.85.108.83
Connecting to cocl.us (cocl.us)|169.48.113.194|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cocl.us/Geospatial_data [following]
--2020-06-17 16:56:28--  https://cocl.us/Geospatial_data
Connecting to cocl.us (cocl.us)|169.48.113.194|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ibm.box.com/shared/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2020-06-17 16:56:31--  https://ibm.box.com/shared/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Resolving ibm.box.com (ibm.box.com)... 107.152.29.197
Connecting to ibm.box.com (ibm.box.com)|107.152.29.197|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2020-06-17 16:56:31--  https://ibm.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Reusing existing connection to ibm.box.com:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ibm.ent.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv [following]
--2020-06-17 16:56:31--  https://ibm.ent.box.com/public/static/9afzr83pps4pwf2smjjcf1y5mvgb18rr.csv
Resolving ibm.ent.box.com (ibm.ent.box.com)... 107.152.27.211
Connecting to ibm.ent.box.com (ibm.ent.box.com)|107.152.27.211|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://public.boxcloud.com/d/1/b1!zXAFuQuH82P7olFI02py1OaRx5Rf6m1fWiTKxp9C1ULKAeFg2eNEC28xj4TZF0DRkFSkzQMXRtajQckVs-fpMC7HcUaO7zKJiEa0BYbtkOQqph7a-qqbt5_UwqqxMxEq2F6BysFLFHCT0SLQ9YzDkwk63V6Ii1ARSbJ7J1SyO0Jj5KsvHneRYdIfJdVnFA6Sc7bnKfIm1nQfKa21xgCSNLiJ6K-6ZFvNUU_wWW5TnDVYy_Rpw-Ka2k5IL6_NDnuDfJdgOrK6sybBwvaKzkmhzTNHu3kHBZMDQdeF-kFtMN0I0djnna17KUH8QvoKvukB2Mxq4qzLzUqQgAAIp--0DBoXDqsmom_OvuhWG_c5BpwnPVSoZ2sCwTjUW4IsFlGAiG314QfBOaLsmXTE0GOKYoQNsxNvBgq3bYD3xLsJtFRM_E-17mX7-LfRKU1JsbhSETkQOBSEK0U7MGnN7d_IShd_VyxY36xMGyq7tiBllYNkK7O4d10EYlUO90zIQTkaEasx-Ls_Fpn79ZJL7f_9jG3D7YWpxv7rNJIExfOIdSQ8baw8CSKXJw8Hr3HIivJRUX3UdYRYExk2PGx4Lei1j667gNACW-LaUPXEiUGN9f3WfED9prvK5fKOcdnxv3lgU9IS3jtHCYYNtIbQxGploV4V53RPJXTGdQn1zgA9b4ycCbL4oC2jGxRd0W38-qdNwYeMGqvWc25wSJgYs1MR3HW57U715k-P4S9g7uBHOG--2wVnIrPTxIddF5ZJNDvk4IvwDLpQl-B6oLN_K-xraeJwk0Ry_znvGzNG5kqJwpdy3MfaOui99mjBGbELTCI9pyqdImbXfbbNmM5x9Qj0GVNJ6E5hTKQNNBfwGCMDBq-jAUidS6wyLVzmvuiCcrZmuJnhSBasvjwQUEasXu0GzmumwajZTyTHQGGqgZJil-apaMS2tkVr-2QMH1IlCPDnd4J4urNk8M7EUIadV2UQmVnKVLdzW-BU9rpwphMkB-SVn8_9rOkO5bLLxrqOrVwGiN7TEcSJR7iOs6RNv8zaSieDCC5k92_saAye2OPyAT8T5KUtWGTPDHZ_0hBu2Yn1f-Cwfb54QBg_KfhJ634hb4FTah59EAvWN1XmRXaAL-MoMhVune21KFlDm1p80VbHlt1gyBegC7IPtDrLghrejuRZcw0LSJSJq5Dcom6qyJlTzMzOoK5TC7QKqu3iLu4wcjVmxjJQdJC9cgYgIsy1jRM1e24_k_-O7mhi24N8_V1yQ3-WIvVZOuc5Tz3pb_nlyodZhim0jKTRyPtW8BVRfJwxAyZIKHon2vm7A1EUVdZRwPq8FRg-RXtd76-JckURohZnpgqJH8WwI4j45ZLJu8oVGl7U0kBoiR0tMng24zKoTfi96WC0uRJrlyg4DUJ5fcvLa5bYCRjZUQJVcOasW7Bu5bH3wzBzRB2lLvXK2tjK/download [following]
--2020-06-17 16:56:31--  https://public.boxcloud.com/d/1/b1!zXAFuQuH82P7olFI02py1OaRx5Rf6m1fWiTKxp9C1ULKAeFg2eNEC28xj4TZF0DRkFSkzQMXRtajQckVs-fpMC7HcUaO7zKJiEa0BYbtkOQqph7a-qqbt5_UwqqxMxEq2F6BysFLFHCT0SLQ9YzDkwk63V6Ii1ARSbJ7J1SyO0Jj5KsvHneRYdIfJdVnFA6Sc7bnKfIm1nQfKa21xgCSNLiJ6K-6ZFvNUU_wWW5TnDVYy_Rpw-Ka2k5IL6_NDnuDfJdgOrK6sybBwvaKzkmhzTNHu3kHBZMDQdeF-kFtMN0I0djnna17KUH8QvoKvukB2Mxq4qzLzUqQgAAIp--0DBoXDqsmom_OvuhWG_c5BpwnPVSoZ2sCwTjUW4IsFlGAiG314QfBOaLsmXTE0GOKYoQNsxNvBgq3bYD3xLsJtFRM_E-17mX7-LfRKU1JsbhSETkQOBSEK0U7MGnN7d_IShd_VyxY36xMGyq7tiBllYNkK7O4d10EYlUO90zIQTkaEasx-Ls_Fpn79ZJL7f_9jG3D7YWpxv7rNJIExfOIdSQ8baw8CSKXJw8Hr3HIivJRUX3UdYRYExk2PGx4Lei1j667gNACW-LaUPXEiUGN9f3WfED9prvK5fKOcdnxv3lgU9IS3jtHCYYNtIbQxGploV4V53RPJXTGdQn1zgA9b4ycCbL4oC2jGxRd0W38-qdNwYeMGqvWc25wSJgYs1MR3HW57U715k-P4S9g7uBHOG--2wVnIrPTxIddF5ZJNDvk4IvwDLpQl-B6oLN_K-xraeJwk0Ry_znvGzNG5kqJwpdy3MfaOui99mjBGbELTCI9pyqdImbXfbbNmM5x9Qj0GVNJ6E5hTKQNNBfwGCMDBq-jAUidS6wyLVzmvuiCcrZmuJnhSBasvjwQUEasXu0GzmumwajZTyTHQGGqgZJil-apaMS2tkVr-2QMH1IlCPDnd4J4urNk8M7EUIadV2UQmVnKVLdzW-BU9rpwphMkB-SVn8_9rOkO5bLLxrqOrVwGiN7TEcSJR7iOs6RNv8zaSieDCC5k92_saAye2OPyAT8T5KUtWGTPDHZ_0hBu2Yn1f-Cwfb54QBg_KfhJ634hb4FTah59EAvWN1XmRXaAL-MoMhVune21KFlDm1p80VbHlt1gyBegC7IPtDrLghrejuRZcw0LSJSJq5Dcom6qyJlTzMzOoK5TC7QKqu3iLu4wcjVmxjJQdJC9cgYgIsy1jRM1e24_k_-O7mhi24N8_V1yQ3-WIvVZOuc5Tz3pb_nlyodZhim0jKTRyPtW8BVRfJwxAyZIKHon2vm7A1EUVdZRwPq8FRg-RXtd76-JckURohZnpgqJH8WwI4j45ZLJu8oVGl7U0kBoiR0tMng24zKoTfi96WC0uRJrlyg4DUJ5fcvLa5bYCRjZUQJVcOasW7Bu5bH3wzBzRB2lLvXK2tjK/download
Resolving public.boxcloud.com (public.boxcloud.com)... 107.152.27.200
Connecting to public.boxcloud.com (public.boxcloud.com)|107.152.27.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2891 (2.8K) [text/csv]
Saving to: ‘Geospatial_Coordinates.csv’

Geospatial_Coordina 100%[===================>]   2.82K  --.-KB/s    in 0.001s

2020-06-17 16:56:32 (1.91 MB/s) - ‘Geospatial_Coordinates.csv’ saved [2891/2891]

In [61]:
df2 = pd.read_csv('Geospatial_Coordinates.csv')
df2.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [62]:
df2.rename(columns={"Postal Code": "PostalCode"}, inplace = True)
df2

    PostalCode   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
..         ...        ...        ...
98         M9N  43.706876 -79.518188
99         M9P  43.696319 -79.532242
100        M9R  43.688905 -79.554724
101        M9V  43.739416 -79.588437
102        M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [64]:
mergedf = pd.merge(df, df2)
mergedf.head(10)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
5,M1J,Scarborough,Scarborough Village,43.744734,-79.239476
6,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park",43.727929,-79.262029
7,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge",43.711112,-79.284577
8,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West",43.716316,-79.239476
9,M1N,Scarborough,"Birch Cliff, Cliffside West",43.692657,-79.264848